/*${date}*/

/**********************************************************************
 * ${file_name}
 *
 * generated by : embedded software producer / ${generator}
 **********************************************************************/

/**********************************************************************
 * This file describes the task descriptor structure.
 * The task descriptor is a structure containing field specific to targets
 * and additional common members.
 * This file must exist and have this exact name
 **********************************************************************/

#ifndef RTE_HOOK_CFG_H
#define RTE_HOOK_CFG_H

#define RTE_ReadHook_Flashlight_timer_InputSignal_On
#define RTE_WriteHook_Flashlight_timer_InputSignal_On
#define RTE_ReadHook_Flashlight_timer_InputSignal_Off
#define RTE_WriteHook_Flashlight_timer_InputSignal_Off
#define RTE_ReadHook_Flashlight_light_InputSignal_Tick
#define RTE_WriteHook_Flashlight_light_InputSignal_Tick
#define RTE_ReadHook_Flashlight_timer_light_On
#define RTE_TriggerHook_Flashlight_timer_light_On
#define RTE_ReadHook_Flashlight_timer_light_Off
#define RTE_TriggerHook_Flashlight_timer_light_Off
#define RTE_ReadHook_Flashlight_timer_light_Tick
#define RTE_TriggerHook_Flashlight_timer_light_Tick
#define RTE_ReadHook_Flashlight_timer_light_snd
#define RTE_WriteHook_Flashlight_timer_light_snd
#define RTE_ReadHook_Flashlight_timer_control_On
#define RTE_WriteHook_Flashlight_timer_control_On
#define RTE_ReadHook_Flashlight_timer_control_Off
#define RTE_WriteHook_Flashlight_timer_control_Off
#define RTE_ReadHook_Flashlight_timer_control_Tick
#define RTE_WriteHook_Flashlight_timer_control_Tick
#define RTE_ReadHook_Flashlight_timer_control_snd
#define RTE_WriteHook_Flashlight_timer_control_snd
#define RTE_ReadHook_Flashlight_light_light_On
#define RTE_WriteHook_Flashlight_light_light_On
#define RTE_ReadHook_Flashlight_light_light_Off
#define RTE_WriteHook_Flashlight_light_light_Off
#define RTE_ReadHook_Flashlight_light_light_Tick
#define RTE_WriteHook_Flashlight_light_light_Tick
#define RTE_ReadHook_Flashlight_light_light_snd
#define RTE_WriteHook_Flashlight_light_light_snd
#define RTE_ReadHook_Flashlight_light_pout_io
#define RTE_WriteHook_Flashlight_light_pout_io
#define RTE_ReadHook_Flashlight_button_control_On
#define RTE_TriggerHook_Flashlight_button_control_On
#define RTE_ReadHook_Flashlight_button_control_Off
#define RTE_TriggerHook_Flashlight_button_control_Off
#define RTE_ReadHook_Flashlight_button_control_Tick
#define RTE_TriggerHook_Flashlight_button_control_Tick
#define RTE_ReadHook_Flashlight_button_control_snd
#define RTE_WriteHook_Flashlight_button_control_snd
#define RTE_ReadHook_Flashlight_button_pin_io
#define RTE_WriteHook_Flashlight_button_pin_io
#define RTE_ReadHook_Flashlight_count_countin_io
#define RTE_WriteHook_Flashlight_count_countin_io
#define RTE_ReadHook_Flashlight_count_fp_counts_data
#define RTE_WriteHook_Flashlight_count_fp_counts_data

#endif /* RTE_HOOK_CFG_H */
