/*2023-03-30T15:07:49.472059398Z*/

/**********************************************************************
 * Functions_Send_Tick.c
 *
 * generated by : embedded software producer/ESPActivityCCodeGen 0.0.1
 **********************************************************************/

/* Application code for activity "Send Tick" */

#include "Functions_Send_Tick.h"

#include <string.h>
#define ACTIVITY_NAME   "Send Tick"
#define ACTIVITY_PFX    Send_Tick
#define ACTIVIT_ID      _2022x_1ad00ce_1659688719563_974354_4325
#define ACTIVITY        Functions_Send_Tick_struct

/**********************************************************************
 * default event handlers
 **********************************************************************/
static FUNCTIONS_SEND_TICK_EVENT_T default_peekEvent(ACTIVITY *instance) {
    return instance->EVENT;
}
static FUNCTIONS_SEND_TICK_EVENT_T default_nextEvent(ACTIVITY *instance) {
    (void)instance; /* keep Misra happy */
    return FUNCTIONS_SEND_TICK_EVENT_T_NO_EVENT;
}
static Boolean default_sendEvent(ACTIVITY *instance, FUNCTIONS_SEND_TICK_EVENT_T event) {
    Boolean ret = FALSE;
    if(instance->EVENT == FUNCTIONS_SEND_TICK_EVENT_T_NO_EVENT) {
        instance->EVENT = event;
        ret = TRUE;
    }
    return ret;
}

/**********************************************************************
 * helpers
 **********************************************************************/
static inline Boolean isRunning(ACTIVITY *instance) {
    return (instance->flow[0] != 0u) ? TRUE : FALSE;
}

/**********************************************************************
 * activity init code
 **********************************************************************/
void _basic_Functions_Send_Tick_init(ACTIVITY *instance) {
    if(instance->peekEVENT == NULL) {instance->peekEVENT = default_peekEvent;}
    if(instance->nextEVENT == NULL) {instance->nextEVENT = default_nextEvent;}
    if(instance->sendEVENT == NULL) {instance->sendEVENT = default_sendEvent;}
    instance->EVENT = FUNCTIONS_SEND_TICK_EVENT_T_NO_EVENT;

    (void)memset(instance->flow, 0, 1u * sizeof(instance->flow[0]));

    instance->WALL_CLOCK        = (WALLCLOCK_T)0;
}

/**********************************************************************
 * activity exit code
 **********************************************************************/
void _basic_Functions_Send_Tick_end(ACTIVITY *instance) {
    (void)instance; /* keep Misra happy */
}

/**********************************************************************
 * activity step code
 **********************************************************************/
Boolean _basic_Functions_Send_Tick(ACTIVITY *instance) {
    /* initialization */
    if(isRunning(instance) == FALSE) {
        instance->flow[0] = 1u; /* SET_FLOW->SendSignalAction */
        instance->EVENT = instance->peekEVENT(instance);
    }

    if(1u == (instance->flow[0] & 1u)) { /* TST_FLOW<-InitialNode */
        /* node:_2022x_1ad00ce_1659688849673_850040_4448 */
        Boolean success = instance->sendEVENT(instance, FUNCTIONS_SEND_TICK_EVENT_T_Tick);
        if(success != FALSE) {
            instance->flow[0] ^= 1u; /* CLR_FLOW<-InitialNode */
        }
    }

    return (FALSE == isRunning(instance)) ? TRUE : FALSE;
}

/* end of file */
