/*2023-03-30T15:07:49.470484371Z*/

/**********************************************************************
 * Functions_Send_Tick_internal_type.h
 *
 * generated by : embedded software producer/ESPActivityCCodeGen 0.0.1
 **********************************************************************/

#ifndef FUNCTIONS_SEND_TICK_INTERNAL_TYPE_H
#define FUNCTIONS_SEND_TICK_INTERNAL_TYPE_H

/* BEG_USER_CODE(types) do not remove */

#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool    Boolean;
#endif
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int     Integer;
#endif
#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef float   Real;
#endif
#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *  String;
#endif

/* END_USER_CODE(types) do not remove */


#endif
/* end of file */
