/*2023-03-30T15:07:49.428068455Z*/

/**********************************************************************
 * Timer.h
 *
 * generated by : embedded software producer/uml statemachine 0.1.5
 **********************************************************************/

#ifndef TIMER_H
#define TIMER_H

#if defined( __cplusplus) || (defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 199901L))
#include <stdbool.h>
#else
#ifndef bool
#define bool	int
#endif

#ifndef true
#define true	(1==1)
#endif

#ifndef false
#define false	(!true)
#endif
#endif /* stdbool check */

#include "Timer_itf.h"
#include "Timer_Send_Tick.h"

/* BEG_USER_CODE(types) do not remove */

typedef double	WALLCLOCK_T;  /* time type (can be any scalar) */
typedef void *	USERDATA_T;   /* replace this pointer by an anonymous struct if needed. */
#ifndef Boolean_DEFINITION
#define Boolean_DEFINITION
typedef bool	Boolean;
#endif
#ifndef Integer_DEFINITION
#define Integer_DEFINITION
typedef int  	Integer;
#endif
#ifndef Real_DEFINITION
#define Real_DEFINITION
typedef float 	Real;
#endif
#ifndef String_DEFINITION
#define String_DEFINITION
typedef char *	String;
#endif

/* END_USER_CODE(types) do not remove */

#ifndef TRUE
#define TRUE	true
#endif

#ifndef FALSE
#define FALSE	false
#endif

typedef enum {
	TIMER_STATE_T_INITIAL_0,
	TIMER_STATE_T_off,
	TIMER_STATE_T_Ticking,
	TIMER_STATE_T_VOID
} TIMER_STATE_T;

typedef enum {
	TIMER_EVENT_T_Off,
	TIMER_EVENT_T_On,
	TIMER_EVENT_T_NO_EVENT
} TIMER_EVENT_T;

typedef struct {
	/* user data */
	USERDATA_T            	USERDATA;
	
	/* ports */
	Boolean               	light_snd;
	Boolean               	control_snd;
	
	/* sub behaviors */
	Timer_Send_Tick_struct	Ticking_Entry_Send_Tick;
	
	/* internal */
	TIMER_STATE_T         	CURRENT_STATE_0;
	WALLCLOCK_T           	WALL_CLOCK;
	WALLCLOCK_T           	ENTER_CLOCK_0;
	TIMER_EVENT_T         	EVENT;
	Boolean               	FIRST;
	Boolean               	DONE_ACTIVITY;
} Timer_struct;

void _basic_Timer_init(Timer_struct *instance);
void _basic_Timer(Timer_struct *instance);
void _basic_Timer_end(Timer_struct *instance);

/* BEG_USER_CODE(extra-header) do not remove */

/* insert here things you need to add to the header file */

/* END_USER_CODE(extra-header) do not remove */

#endif /*TIMER_H*/
/* end of file */
