/*2023-03-30T15:05:00.503224516Z*/

/**********************************************************************
 * rte_cfg.c
 *
 * generated by : embedded software producer / runtime code gen 1.0.0
 **********************************************************************/

#include "rte_cfg.h"
#include "rte_hook.h"

#define RTE_C /* Macro to include only some specific parts of include files */
#include "Counter_itf.h"
#include "Timer_itf.h"
#include "Button_itf.h"
#include "Light_itf.h"

#ifdef RTE_DEBUG
#include <stdio.h>
#define debug(...) printf(__VA_ARGS__); fflush(stdout)
#else
#define debug(...)
#endif


task_descriptor task_descriptors[NUMBER_OF_TASKS];

static function_ptr task0_functions[4];
static rte_instance_ptr task0_rteInstances[4];


/*
 * Rte instances declaration
 */
Rte_Timer_Struct Flashlight_timer_inst;
Rte_Light_Struct Flashlight_light_inst;
Rte_Button_Struct Flashlight_button_inst;
Rte_Counter_Struct Flashlight_count_inst;

/*
 * Shared variables definitions
 */
Boolean from_Flashlight_timer_light_snd;
SignalEvent_On_type from_Flashlight_timer_light_On;
SignalEvent_Off_type from_Flashlight_timer_light_Off;
SignalEvent_Tick_type from_Flashlight_timer_light_Tick;
Boolean from_Flashlight_light_pout_io;
Boolean from_Flashlight_button_control_snd;
SignalEvent_On_type from_Flashlight_button_control_On;
SignalEvent_Off_type from_Flashlight_button_control_Off;
SignalEvent_Tick_type from_Flashlight_button_control_Tick;
Integer from_Flashlight_count_fp_counts_data;
SignalEvent_On_type from_UNCONNECTED_InputSignal_On;
SignalEvent_Off_type from_UNCONNECTED_InputSignal_Off;
SignalEvent_Tick_type from_UNCONNECTED_InputSignal_Tick;
Boolean from_UNCONNECTED_pin_io;

/*
 * Triggering functions
 */
void RTE_Trigger_Flashlight_timer_light_On(void){

	RTE_TriggerHook_Flashlight_timer_light_On_Start(&from_Flashlight_timer_light_On);
	debug("DEBUG: RTE_Trigger_Flashlight_timer_light_On: Enter\\\n");

	from_Flashlight_timer_light_On.trigger = 1;
	debug("DEBUG: RTE_Write_Flashlight_timer_light_On: Exit\\\n");
	RTE_TriggerHook_Flashlight_timer_light_On_Return(&from_Flashlight_timer_light_On);
}

void RTE_Trigger_Flashlight_timer_light_Off(void){

	RTE_TriggerHook_Flashlight_timer_light_Off_Start(&from_Flashlight_timer_light_Off);
	debug("DEBUG: RTE_Trigger_Flashlight_timer_light_Off: Enter\\\n");

	from_Flashlight_timer_light_Off.trigger = 1;
	debug("DEBUG: RTE_Write_Flashlight_timer_light_Off: Exit\\\n");
	RTE_TriggerHook_Flashlight_timer_light_Off_Return(&from_Flashlight_timer_light_Off);
}

void RTE_Trigger_Flashlight_timer_light_Tick(void){

	RTE_TriggerHook_Flashlight_timer_light_Tick_Start(&from_Flashlight_timer_light_Tick);
	debug("DEBUG: RTE_Trigger_Flashlight_timer_light_Tick: Enter\\\n");

	from_Flashlight_timer_light_Tick.trigger = 1;

	/* Send Signal on InputSignal port */
	from_UNCONNECTED_InputSignal_Tick.trigger = 1;
	
	debug("DEBUG: RTE_Write_Flashlight_timer_light_Tick: Exit\\\n");
	RTE_TriggerHook_Flashlight_timer_light_Tick_Return(&from_Flashlight_timer_light_Tick);
}

void RTE_Trigger_Flashlight_button_control_On(void){

	RTE_TriggerHook_Flashlight_button_control_On_Start(&from_Flashlight_button_control_On);
	debug("DEBUG: RTE_Trigger_Flashlight_button_control_On: Enter\\\n");

	from_Flashlight_button_control_On.trigger = 1;

	/* Send Signal on InputSignal port */
	from_UNCONNECTED_InputSignal_On.trigger = 1;
	
	debug("DEBUG: RTE_Write_Flashlight_button_control_On: Exit\\\n");
	RTE_TriggerHook_Flashlight_button_control_On_Return(&from_Flashlight_button_control_On);
}

void RTE_Trigger_Flashlight_button_control_Off(void){

	RTE_TriggerHook_Flashlight_button_control_Off_Start(&from_Flashlight_button_control_Off);
	debug("DEBUG: RTE_Trigger_Flashlight_button_control_Off: Enter\\\n");

	from_Flashlight_button_control_Off.trigger = 1;

	/* Send Signal on InputSignal port */
	from_UNCONNECTED_InputSignal_Off.trigger = 1;
	
	debug("DEBUG: RTE_Write_Flashlight_button_control_Off: Exit\\\n");
	RTE_TriggerHook_Flashlight_button_control_Off_Return(&from_Flashlight_button_control_Off);
}

void RTE_Trigger_Flashlight_button_control_Tick(void){

	RTE_TriggerHook_Flashlight_button_control_Tick_Start(&from_Flashlight_button_control_Tick);
	debug("DEBUG: RTE_Trigger_Flashlight_button_control_Tick: Enter\\\n");

	from_Flashlight_button_control_Tick.trigger = 1;
	debug("DEBUG: RTE_Write_Flashlight_button_control_Tick: Exit\\\n");
	RTE_TriggerHook_Flashlight_button_control_Tick_Return(&from_Flashlight_button_control_Tick);
}


/*
 * Send functions
 */
void RTE_Write_Flashlight_timer_light_snd(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx = 0;

	RTE_WriteHook_Flashlight_timer_light_snd_Start(&from_Flashlight_timer_light_snd);
	debug("DEBUG: RTE_Write_Flashlight_timer_light_snd: Enter\\\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &from_Flashlight_timer_light_snd)[byteIdx] = ((char*) data)[byteIdx];
	}

	debug("DEBUG: RTE_Write_Flashlight_timer_light_snd: Exit\\\n");
	RTE_WriteHook_Flashlight_timer_light_snd_Return(&from_Flashlight_timer_light_snd);
}

void RTE_Write_Flashlight_light_pout_io(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx = 0;

	RTE_WriteHook_Flashlight_light_pout_io_Start(&from_Flashlight_light_pout_io);
	debug("DEBUG: RTE_Write_Flashlight_light_pout_io: Enter\\\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &from_Flashlight_light_pout_io)[byteIdx] = ((char*) data)[byteIdx];
	}

	debug("DEBUG: RTE_Write_Flashlight_light_pout_io: Exit\\\n");
	RTE_WriteHook_Flashlight_light_pout_io_Return(&from_Flashlight_light_pout_io);
}

void RTE_Write_Flashlight_button_control_snd(Boolean* data){
	// Copy byte by byte
	unsigned int byteIdx = 0;

	RTE_WriteHook_Flashlight_button_control_snd_Start(&from_Flashlight_button_control_snd);
	debug("DEBUG: RTE_Write_Flashlight_button_control_snd: Enter\\\n");

	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) &from_Flashlight_button_control_snd)[byteIdx] = ((char*) data)[byteIdx];
	}

	debug("DEBUG: RTE_Write_Flashlight_button_control_snd: Exit\\\n");
	RTE_WriteHook_Flashlight_button_control_snd_Return(&from_Flashlight_button_control_snd);
}

void RTE_Write_Flashlight_count_fp_counts_data(Integer* data){
	// Copy byte by byte
	unsigned int byteIdx = 0;

	RTE_WriteHook_Flashlight_count_fp_counts_data_Start(&from_Flashlight_count_fp_counts_data);
	debug("DEBUG: RTE_Write_Flashlight_count_fp_counts_data: Enter\\\n");

	for(byteIdx=0; byteIdx < sizeof(Integer); byteIdx++){
		((char*) &from_Flashlight_count_fp_counts_data)[byteIdx] = ((char*) data)[byteIdx];
	}

	debug("DEBUG: RTE_Write_Flashlight_count_fp_counts_data: Exit\\\n");
	RTE_WriteHook_Flashlight_count_fp_counts_data_Return(&from_Flashlight_count_fp_counts_data);
}


/*
 * Read functions
 */
void RTE_Read_Flashlight_light_light_snd(Boolean* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_light_light_snd_Start(&from_Flashlight_timer_light_snd);
	RTE_ReadHook_Flashlight_light_light_snd_Return(&from_Flashlight_timer_light_snd);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_timer_light_snd)[byteIdx];
	}
}

void RTE_Read_Flashlight_light_light_On(SignalEvent_On_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_light_light_On_Start(&from_Flashlight_timer_light_On);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_timer_light_On)[byteIdx];
	}
	from_Flashlight_timer_light_On.trigger = 0;
	RTE_ReadHook_Flashlight_light_light_On_Return(&from_Flashlight_timer_light_On);
}

void RTE_Read_Flashlight_light_light_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_light_light_Off_Start(&from_Flashlight_timer_light_Off);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_timer_light_Off)[byteIdx];
	}
	from_Flashlight_timer_light_Off.trigger = 0;
	RTE_ReadHook_Flashlight_light_light_Off_Return(&from_Flashlight_timer_light_Off);
}

void RTE_Read_Flashlight_light_light_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_light_light_Tick_Start(&from_Flashlight_timer_light_Tick);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_timer_light_Tick)[byteIdx];
	}
	from_Flashlight_timer_light_Tick.trigger = 0;
	RTE_ReadHook_Flashlight_light_light_Tick_Return(&from_Flashlight_timer_light_Tick);
}

void RTE_Read_Flashlight_timer_control_snd(Boolean* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_timer_control_snd_Start(&from_Flashlight_button_control_snd);
	RTE_ReadHook_Flashlight_timer_control_snd_Return(&from_Flashlight_button_control_snd);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_button_control_snd)[byteIdx];
	}
}

void RTE_Read_Flashlight_timer_control_On(SignalEvent_On_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_timer_control_On_Start(&from_Flashlight_button_control_On);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_button_control_On)[byteIdx];
	}
	from_Flashlight_button_control_On.trigger = 0;
	RTE_ReadHook_Flashlight_timer_control_On_Return(&from_Flashlight_button_control_On);
}

void RTE_Read_Flashlight_timer_control_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_timer_control_Off_Start(&from_Flashlight_button_control_Off);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_button_control_Off)[byteIdx];
	}
	from_Flashlight_button_control_Off.trigger = 0;
	RTE_ReadHook_Flashlight_timer_control_Off_Return(&from_Flashlight_button_control_Off);
}

void RTE_Read_Flashlight_timer_control_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_timer_control_Tick_Start(&from_Flashlight_button_control_Tick);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_button_control_Tick)[byteIdx];
	}
	from_Flashlight_button_control_Tick.trigger = 0;
	RTE_ReadHook_Flashlight_timer_control_Tick_Return(&from_Flashlight_button_control_Tick);
}

void RTE_Read_Flashlight_count_countin_io(Boolean* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_count_countin_io_Start(&from_Flashlight_light_pout_io);
	RTE_ReadHook_Flashlight_count_countin_io_Return(&from_Flashlight_light_pout_io);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_Flashlight_light_pout_io)[byteIdx];
	}
}

void RTE_Read_Flashlight_timer_InputSignal_On(SignalEvent_On_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_timer_InputSignal_On_Start(&from_UNCONNECTED_InputSignal_On);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_On_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_InputSignal_On)[byteIdx];
	}
	from_UNCONNECTED_InputSignal_On.trigger = 0;
	RTE_ReadHook_Flashlight_timer_InputSignal_On_Return(&from_UNCONNECTED_InputSignal_On);
}

void RTE_Read_Flashlight_timer_InputSignal_Off(SignalEvent_Off_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_timer_InputSignal_Off_Start(&from_UNCONNECTED_InputSignal_Off);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Off_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_InputSignal_Off)[byteIdx];
	}
	from_UNCONNECTED_InputSignal_Off.trigger = 0;
	RTE_ReadHook_Flashlight_timer_InputSignal_Off_Return(&from_UNCONNECTED_InputSignal_Off);
}

void RTE_Read_Flashlight_light_InputSignal_Tick(SignalEvent_Tick_type* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_light_InputSignal_Tick_Start(&from_UNCONNECTED_InputSignal_Tick);
	for(byteIdx=0; byteIdx < sizeof(SignalEvent_Tick_type); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_InputSignal_Tick)[byteIdx];
	}
	from_UNCONNECTED_InputSignal_Tick.trigger = 0;
	RTE_ReadHook_Flashlight_light_InputSignal_Tick_Return(&from_UNCONNECTED_InputSignal_Tick);
}

void RTE_Read_Flashlight_button_pin_io(Boolean* data){
	unsigned int byteIdx = 0;

	RTE_ReadHook_Flashlight_button_pin_io_Start(&from_UNCONNECTED_pin_io);
	RTE_ReadHook_Flashlight_button_pin_io_Return(&from_UNCONNECTED_pin_io);
	for(byteIdx=0; byteIdx < sizeof(Boolean); byteIdx++){
		((char*) data)[byteIdx] = ((char*) &from_UNCONNECTED_pin_io)[byteIdx];
	}
}


/*
 * Server call functions
 */

/*
 * Map the communication APIs to component instances
 */
void component_instances_init(void){
  /* Timer Rte Instance configuration */
  /* Write functions */
  Flashlight_timer_inst.Write_light_snd = &RTE_Write_Flashlight_timer_light_snd;
  /* Trigger functions */
  Flashlight_timer_inst.Trigger_light_On = &RTE_Trigger_Flashlight_timer_light_On;
  Flashlight_timer_inst.Trigger_light_Off = &RTE_Trigger_Flashlight_timer_light_Off;
  Flashlight_timer_inst.Trigger_light_Tick = &RTE_Trigger_Flashlight_timer_light_Tick;
  /* Read functions */
  Flashlight_timer_inst.Read_control_snd = &RTE_Read_Flashlight_timer_control_snd;
  Flashlight_timer_inst.Read_control_On = &RTE_Read_Flashlight_timer_control_On;
  Flashlight_timer_inst.Read_control_Off = &RTE_Read_Flashlight_timer_control_Off;
  Flashlight_timer_inst.Read_control_Tick = &RTE_Read_Flashlight_timer_control_Tick;
  Flashlight_timer_inst.Read_InputSignal_On = &RTE_Read_Flashlight_timer_InputSignal_On;
  Flashlight_timer_inst.Read_InputSignal_Off = &RTE_Read_Flashlight_timer_InputSignal_Off;
  /* Server call functions */
  Flashlight_timer_inst.period = 0.05;
  /* Timer Rte Instance configuration */

  /* Light Rte Instance configuration */
  /* Write functions */
  Flashlight_light_inst.Write_pout_io = &RTE_Write_Flashlight_light_pout_io;
  /* Trigger functions */
  /* Read functions */
  Flashlight_light_inst.Read_light_snd = &RTE_Read_Flashlight_light_light_snd;
  Flashlight_light_inst.Read_light_On = &RTE_Read_Flashlight_light_light_On;
  Flashlight_light_inst.Read_light_Off = &RTE_Read_Flashlight_light_light_Off;
  Flashlight_light_inst.Read_light_Tick = &RTE_Read_Flashlight_light_light_Tick;
  Flashlight_light_inst.Read_InputSignal_Tick = &RTE_Read_Flashlight_light_InputSignal_Tick;
  /* Server call functions */
  Flashlight_light_inst.period = 0.05;
  /* Light Rte Instance configuration */

  /* Button Rte Instance configuration */
  /* Write functions */
  Flashlight_button_inst.Write_control_snd = &RTE_Write_Flashlight_button_control_snd;
  /* Trigger functions */
  Flashlight_button_inst.Trigger_control_On = &RTE_Trigger_Flashlight_button_control_On;
  Flashlight_button_inst.Trigger_control_Off = &RTE_Trigger_Flashlight_button_control_Off;
  Flashlight_button_inst.Trigger_control_Tick = &RTE_Trigger_Flashlight_button_control_Tick;
  /* Read functions */
  Flashlight_button_inst.Read_pin_io = &RTE_Read_Flashlight_button_pin_io;
  /* Server call functions */
  Flashlight_button_inst.period = 0.05;
  /* Button Rte Instance configuration */

  /* Counter Rte Instance configuration */
  /* Write functions */
  Flashlight_count_inst.Write_fp_counts_data = &RTE_Write_Flashlight_count_fp_counts_data;
  /* Trigger functions */
  /* Read functions */
  Flashlight_count_inst.Read_countin_io = &RTE_Read_Flashlight_count_countin_io;
  /* Server call functions */
  Flashlight_count_inst.period = 0.05;
  /* Counter Rte Instance configuration */

}

/*
 * Tasks initialization
 *
 * A56 - 12/6/2019: Initialization of global variables is done at runtime
 * because for some boards or compiling option static initialization fails
 * True for RIOT but code below could be done at variable declaration for Adaptive
 */
void task_descriptors_init(void){
  /* Runnable to task mapping */
  task0_functions[0] = (function_ptr)Timer_Timer;
  task0_rteInstances[0] = &Flashlight_timer_inst;
  /* Runnable to task mapping */
  task0_functions[1] = (function_ptr)Light_Light;
  task0_rteInstances[1] = &Flashlight_light_inst;
  /* Runnable to task mapping */
  task0_functions[2] = (function_ptr)Button_Button;
  task0_rteInstances[2] = &Flashlight_button_inst;
  /* Runnable to task mapping */
  task0_functions[3] = (function_ptr)Counter_OB_cnt;
  task0_rteInstances[3] = &Flashlight_count_inst;

  /* Periodic task task0 configuration */
  task_descriptors[0].type = PERIODIC;
  task_descriptors[0].period = 50;
  task_descriptors[0].functions = task0_functions;
  task_descriptors[0].rte_instances = task0_rteInstances;
  task_descriptors[0].nfunctions = 4;


}

void components_init(void) {
	Timer_Timer_init(&Flashlight_timer_inst);
	Light_Light_init(&Flashlight_light_inst);
	Button_Button_init(&Flashlight_button_inst);
	Counter_OB_cnt_init(&Flashlight_count_inst);
}
