/*2023-03-30T15:05:00.503240603Z*/

/**********************************************************************
 * rte_hook.h
 *
 * generated by : embedded software producer / runtime code gen 1.0.0
 **********************************************************************/

#ifndef RTE_HOOK_H
#define RTE_HOOK_H

#include "rte_hook_cfg.h"

#if defined(RTE_ReadHook_Flashlight_light_light_snd)
#undef ReadHook_Flashlight_light_light_snd
extern void RTE_ReadHook_Flashlight_light_light_snd_Start(Boolean* from_Flashlight_timer_light_snd);
extern void RTE_ReadHook_Flashlight_light_light_snd_Return(Boolean* from_Flashlight_timer_light_snd);
#else
#define RTE_ReadHook_Flashlight_light_light_snd_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_light_light_snd_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_light_light_snd */

#if defined(RTE_ReadHook_Flashlight_light_light_On)
#undef ReadHook_Flashlight_light_light_On
extern void RTE_ReadHook_Flashlight_light_light_On_Start(SignalEvent_On_type* from_Flashlight_timer_light_On);
extern void RTE_ReadHook_Flashlight_light_light_On_Return(SignalEvent_On_type* from_Flashlight_timer_light_On);
#else
#define RTE_ReadHook_Flashlight_light_light_On_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_light_light_On_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_light_light_On */

#if defined(RTE_ReadHook_Flashlight_light_light_Off)
#undef ReadHook_Flashlight_light_light_Off
extern void RTE_ReadHook_Flashlight_light_light_Off_Start(SignalEvent_Off_type* from_Flashlight_timer_light_Off);
extern void RTE_ReadHook_Flashlight_light_light_Off_Return(SignalEvent_Off_type* from_Flashlight_timer_light_Off);
#else
#define RTE_ReadHook_Flashlight_light_light_Off_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_light_light_Off_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_light_light_Off */

#if defined(RTE_ReadHook_Flashlight_light_light_Tick)
#undef ReadHook_Flashlight_light_light_Tick
extern void RTE_ReadHook_Flashlight_light_light_Tick_Start(SignalEvent_Tick_type* from_Flashlight_timer_light_Tick);
extern void RTE_ReadHook_Flashlight_light_light_Tick_Return(SignalEvent_Tick_type* from_Flashlight_timer_light_Tick);
#else
#define RTE_ReadHook_Flashlight_light_light_Tick_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_light_light_Tick_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_light_light_Tick */

#if defined(RTE_ReadHook_Flashlight_timer_control_snd)
#undef ReadHook_Flashlight_timer_control_snd
extern void RTE_ReadHook_Flashlight_timer_control_snd_Start(Boolean* from_Flashlight_button_control_snd);
extern void RTE_ReadHook_Flashlight_timer_control_snd_Return(Boolean* from_Flashlight_button_control_snd);
#else
#define RTE_ReadHook_Flashlight_timer_control_snd_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_timer_control_snd_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_timer_control_snd */

#if defined(RTE_ReadHook_Flashlight_timer_control_On)
#undef ReadHook_Flashlight_timer_control_On
extern void RTE_ReadHook_Flashlight_timer_control_On_Start(SignalEvent_On_type* from_Flashlight_button_control_On);
extern void RTE_ReadHook_Flashlight_timer_control_On_Return(SignalEvent_On_type* from_Flashlight_button_control_On);
#else
#define RTE_ReadHook_Flashlight_timer_control_On_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_timer_control_On_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_timer_control_On */

#if defined(RTE_ReadHook_Flashlight_timer_control_Off)
#undef ReadHook_Flashlight_timer_control_Off
extern void RTE_ReadHook_Flashlight_timer_control_Off_Start(SignalEvent_Off_type* from_Flashlight_button_control_Off);
extern void RTE_ReadHook_Flashlight_timer_control_Off_Return(SignalEvent_Off_type* from_Flashlight_button_control_Off);
#else
#define RTE_ReadHook_Flashlight_timer_control_Off_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_timer_control_Off_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_timer_control_Off */

#if defined(RTE_ReadHook_Flashlight_timer_control_Tick)
#undef ReadHook_Flashlight_timer_control_Tick
extern void RTE_ReadHook_Flashlight_timer_control_Tick_Start(SignalEvent_Tick_type* from_Flashlight_button_control_Tick);
extern void RTE_ReadHook_Flashlight_timer_control_Tick_Return(SignalEvent_Tick_type* from_Flashlight_button_control_Tick);
#else
#define RTE_ReadHook_Flashlight_timer_control_Tick_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_timer_control_Tick_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_timer_control_Tick */

#if defined(RTE_ReadHook_Flashlight_count_countin_io)
#undef ReadHook_Flashlight_count_countin_io
extern void RTE_ReadHook_Flashlight_count_countin_io_Start(Boolean* from_Flashlight_light_pout_io);
extern void RTE_ReadHook_Flashlight_count_countin_io_Return(Boolean* from_Flashlight_light_pout_io);
#else
#define RTE_ReadHook_Flashlight_count_countin_io_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_count_countin_io_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_count_countin_io */

#if defined(RTE_ReadHook_Flashlight_timer_InputSignal_On)
#undef ReadHook_Flashlight_timer_InputSignal_On
extern void RTE_ReadHook_Flashlight_timer_InputSignal_On_Start(SignalEvent_On_type* from_UNCONNECTED_InputSignal_On);
extern void RTE_ReadHook_Flashlight_timer_InputSignal_On_Return(SignalEvent_On_type* from_UNCONNECTED_InputSignal_On);
#else
#define RTE_ReadHook_Flashlight_timer_InputSignal_On_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_timer_InputSignal_On_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_timer_InputSignal_On */

#if defined(RTE_ReadHook_Flashlight_timer_InputSignal_Off)
#undef ReadHook_Flashlight_timer_InputSignal_Off
extern void RTE_ReadHook_Flashlight_timer_InputSignal_Off_Start(SignalEvent_Off_type* from_UNCONNECTED_InputSignal_Off);
extern void RTE_ReadHook_Flashlight_timer_InputSignal_Off_Return(SignalEvent_Off_type* from_UNCONNECTED_InputSignal_Off);
#else
#define RTE_ReadHook_Flashlight_timer_InputSignal_Off_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_timer_InputSignal_Off_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_timer_InputSignal_Off */

#if defined(RTE_ReadHook_Flashlight_light_InputSignal_Tick)
#undef ReadHook_Flashlight_light_InputSignal_Tick
extern void RTE_ReadHook_Flashlight_light_InputSignal_Tick_Start(SignalEvent_Tick_type* from_UNCONNECTED_InputSignal_Tick);
extern void RTE_ReadHook_Flashlight_light_InputSignal_Tick_Return(SignalEvent_Tick_type* from_UNCONNECTED_InputSignal_Tick);
#else
#define RTE_ReadHook_Flashlight_light_InputSignal_Tick_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_light_InputSignal_Tick_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_light_InputSignal_Tick */

#if defined(RTE_ReadHook_Flashlight_button_pin_io)
#undef ReadHook_Flashlight_button_pin_io
extern void RTE_ReadHook_Flashlight_button_pin_io_Start(Boolean* from_UNCONNECTED_pin_io);
extern void RTE_ReadHook_Flashlight_button_pin_io_Return(Boolean* from_UNCONNECTED_pin_io);
#else
#define RTE_ReadHook_Flashlight_button_pin_io_Start(value)  ((void) (0))
#define RTE_ReadHook_Flashlight_button_pin_io_Return(value)  ((void) (0))
#endif /* ReadHook_Flashlight_button_pin_io */


#if defined(RTE_WriteHook_Flashlight_timer_light_snd)
#undef WriteHook_Flashlight_timer_light_snd
extern void RTE_WriteHook_Flashlight_timer_light_snd_Start(Boolean* from_Flashlight_timer_light_snd);
extern void RTE_WriteHook_Flashlight_timer_light_snd_Return(Boolean* from_Flashlight_timer_light_snd);
#else
#define RTE_WriteHook_Flashlight_timer_light_snd_Start(value)  ((void) (0))
#define RTE_WriteHook_Flashlight_timer_light_snd_Return(value)  ((void) (0))
#endif /* WriteHook_Flashlight_timer_light_snd */

#if defined(RTE_WriteHook_Flashlight_light_pout_io)
#undef WriteHook_Flashlight_light_pout_io
extern void RTE_WriteHook_Flashlight_light_pout_io_Start(Boolean* from_Flashlight_light_pout_io);
extern void RTE_WriteHook_Flashlight_light_pout_io_Return(Boolean* from_Flashlight_light_pout_io);
#else
#define RTE_WriteHook_Flashlight_light_pout_io_Start(value)  ((void) (0))
#define RTE_WriteHook_Flashlight_light_pout_io_Return(value)  ((void) (0))
#endif /* WriteHook_Flashlight_light_pout_io */

#if defined(RTE_WriteHook_Flashlight_button_control_snd)
#undef WriteHook_Flashlight_button_control_snd
extern void RTE_WriteHook_Flashlight_button_control_snd_Start(Boolean* from_Flashlight_button_control_snd);
extern void RTE_WriteHook_Flashlight_button_control_snd_Return(Boolean* from_Flashlight_button_control_snd);
#else
#define RTE_WriteHook_Flashlight_button_control_snd_Start(value)  ((void) (0))
#define RTE_WriteHook_Flashlight_button_control_snd_Return(value)  ((void) (0))
#endif /* WriteHook_Flashlight_button_control_snd */

#if defined(RTE_WriteHook_Flashlight_count_fp_counts_data)
#undef WriteHook_Flashlight_count_fp_counts_data
extern void RTE_WriteHook_Flashlight_count_fp_counts_data_Start(Integer* from_Flashlight_count_fp_counts_data);
extern void RTE_WriteHook_Flashlight_count_fp_counts_data_Return(Integer* from_Flashlight_count_fp_counts_data);
#else
#define RTE_WriteHook_Flashlight_count_fp_counts_data_Start(value)  ((void) (0))
#define RTE_WriteHook_Flashlight_count_fp_counts_data_Return(value)  ((void) (0))
#endif /* WriteHook_Flashlight_count_fp_counts_data */

#if defined(RTE_TriggerHook_Flashlight_timer_light_On)
#undef TriggerHook_Flashlight_timer_light_On
extern void RTE_TriggerHook_Flashlight_timer_light_On_Start(SignalEvent_On_type* from_Flashlight_timer_light_On);
extern void RTE_TriggerHook_Flashlight_timer_light_On_Return(SignalEvent_On_type* from_Flashlight_timer_light_On);
#else
#define RTE_TriggerHook_Flashlight_timer_light_On_Start(value)  ((void) (0))
#define RTE_TriggerHook_Flashlight_timer_light_On_Return(value)  ((void) (0))
#endif /* TriggerHook_Flashlight_timer_light_On */

#if defined(RTE_TriggerHook_Flashlight_timer_light_Off)
#undef TriggerHook_Flashlight_timer_light_Off
extern void RTE_TriggerHook_Flashlight_timer_light_Off_Start(SignalEvent_Off_type* from_Flashlight_timer_light_Off);
extern void RTE_TriggerHook_Flashlight_timer_light_Off_Return(SignalEvent_Off_type* from_Flashlight_timer_light_Off);
#else
#define RTE_TriggerHook_Flashlight_timer_light_Off_Start(value)  ((void) (0))
#define RTE_TriggerHook_Flashlight_timer_light_Off_Return(value)  ((void) (0))
#endif /* TriggerHook_Flashlight_timer_light_Off */

#if defined(RTE_TriggerHook_Flashlight_timer_light_Tick)
#undef TriggerHook_Flashlight_timer_light_Tick
extern void RTE_TriggerHook_Flashlight_timer_light_Tick_Start(SignalEvent_Tick_type* from_Flashlight_timer_light_Tick);
extern void RTE_TriggerHook_Flashlight_timer_light_Tick_Return(SignalEvent_Tick_type* from_Flashlight_timer_light_Tick);
#else
#define RTE_TriggerHook_Flashlight_timer_light_Tick_Start(value)  ((void) (0))
#define RTE_TriggerHook_Flashlight_timer_light_Tick_Return(value)  ((void) (0))
#endif /* TriggerHook_Flashlight_timer_light_Tick */

#if defined(RTE_TriggerHook_Flashlight_button_control_On)
#undef TriggerHook_Flashlight_button_control_On
extern void RTE_TriggerHook_Flashlight_button_control_On_Start(SignalEvent_On_type* from_Flashlight_button_control_On);
extern void RTE_TriggerHook_Flashlight_button_control_On_Return(SignalEvent_On_type* from_Flashlight_button_control_On);
#else
#define RTE_TriggerHook_Flashlight_button_control_On_Start(value)  ((void) (0))
#define RTE_TriggerHook_Flashlight_button_control_On_Return(value)  ((void) (0))
#endif /* TriggerHook_Flashlight_button_control_On */

#if defined(RTE_TriggerHook_Flashlight_button_control_Off)
#undef TriggerHook_Flashlight_button_control_Off
extern void RTE_TriggerHook_Flashlight_button_control_Off_Start(SignalEvent_Off_type* from_Flashlight_button_control_Off);
extern void RTE_TriggerHook_Flashlight_button_control_Off_Return(SignalEvent_Off_type* from_Flashlight_button_control_Off);
#else
#define RTE_TriggerHook_Flashlight_button_control_Off_Start(value)  ((void) (0))
#define RTE_TriggerHook_Flashlight_button_control_Off_Return(value)  ((void) (0))
#endif /* TriggerHook_Flashlight_button_control_Off */

#if defined(RTE_TriggerHook_Flashlight_button_control_Tick)
#undef TriggerHook_Flashlight_button_control_Tick
extern void RTE_TriggerHook_Flashlight_button_control_Tick_Start(SignalEvent_Tick_type* from_Flashlight_button_control_Tick);
extern void RTE_TriggerHook_Flashlight_button_control_Tick_Return(SignalEvent_Tick_type* from_Flashlight_button_control_Tick);
#else
#define RTE_TriggerHook_Flashlight_button_control_Tick_Start(value)  ((void) (0))
#define RTE_TriggerHook_Flashlight_button_control_Tick_Return(value)  ((void) (0))
#endif /* TriggerHook_Flashlight_button_control_Tick */

#endif /* RTE_HOOK_H */
