/*2023-03-30T15:08:15.059142233Z*/

/**********************************************************************
 * Light_usr.c
 *
 * generated by : embedded software producer/uml statemachine 0.1.5
 **********************************************************************/

#ifdef STATEMACHINE

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define light_snd	instance->light_snd
#define pout_io  	instance->pout_io
#define poutData 	instance->poutData

/* BEG_USER_CODE(header) do not remove */

/* user-modifiable header part */

/* END_USER_CODE(header) do not remove */

/**
 * Function implementing "Do" of State:
 * Off
 * @generated from: _2022x_1ad00ce_1659688246252_961360_4176, _2022x_1_1ad00ce_1677836151283_489740_4246
 */
static void Off_Do(STATEMACHINE *instance) {
/* BEG_USER_CODE(Do_2022x_1ad00ce_1659688246252_961360_4176) do not remove */

	poutData=false;

/* END_USER_CODE(Do_2022x_1ad00ce_1659688246252_961360_4176) do not remove */
}

/**
 * Function implementing "Do" of State:
 * On
 * @generated from: _2022x_1ad00ce_1659688271019_988850_4197, _2022x_1_1ad00ce_1677835558156_715319_4116
 */
static void On_Do(STATEMACHINE *instance) {
/* BEG_USER_CODE(Do_2022x_1ad00ce_1659688271019_988850_4197) do not remove */

	poutData=true;

/* END_USER_CODE(Do_2022x_1ad00ce_1659688271019_988850_4197) do not remove */
}

static void StateMachine_init(STATEMACHINE *instance) {
	poutData = 0;
	
/* BEG_USER_CODE(init_state_machine) do not remove */

	/* do whatever needed */

/* END_USER_CODE(init_state_machine) do not remove */
}

static void StateMachine_end(STATEMACHINE *instance) {
/* BEG_USER_CODE(end_state_machine) do not remove */

	/* do whatever needed */

/* END_USER_CODE(end_state_machine) do not remove */
}

/* BEG_USER_CODE(footer) do not remove */

/* user-modifiable footer part */

/* END_USER_CODE(footer) do not remove */

#endif /* STATEMACHINE */
/* end of file */
