/*2023-03-30T15:08:15.037561175Z*/

/**********************************************************************
 * Light.c
 *
 * generated by : embedded software producer/uml statemachine 0.1.5
 **********************************************************************/

/* Application code for statemachine "Light" */

#include "Light.h"

#define STATEMACHINE_NAME   "Light"
#define STATEMACHINE_PFX    Light
#define STATEMACHINE_ID     _2022x_1ad00ce_1659688246184_266641_4147
#define STATEMACHINE        Light_struct

/**********************************************************************
 * prototypes
 **********************************************************************/
static void Off_Do(STATEMACHINE *instance);
static void On_Do(STATEMACHINE *instance);
static void StateMachine_init(STATEMACHINE *instance);
static void StateMachine_end(STATEMACHINE *instance);

/**********************************************************************
 * handy helpers
 **********************************************************************/
#define light_snd	instance->light_snd
#define pout_io  	instance->pout_io
#define poutData 	instance->poutData

/**********************************************************************
 * state machine
 **********************************************************************/
void _basic_Light(STATEMACHINE *instance) {
	if(instance->FIRST != FALSE) {
		instance->FIRST = FALSE;
		instance->CURRENT_STATE_0 = LIGHT_STATE_T_INITIAL_0;
		/* INITIAL_0 -> Off */
		instance->CURRENT_STATE_0 = LIGHT_STATE_T_Off;
	}
	switch(instance->CURRENT_STATE_0) {
		case LIGHT_STATE_T_Off: {
			instance->DONE_ACTIVITY = TRUE;
			Off_Do(instance); /* Do of LIGHT_STATE_T_Off */
			if( instance->DONE_ACTIVITY == FALSE ) {
				/* RTC reached. Do nothing more here. */;
			} else if( instance->EVENT == LIGHT_EVENT_T_Tick ) {
				/* Off -> On */
				instance->CURRENT_STATE_0 = LIGHT_STATE_T_On;
				instance->EVENT = LIGHT_EVENT_T_NO_EVENT;
			} else {
				/* nothing */;
			}
			break; /* end of Off */
		}
		case LIGHT_STATE_T_On: {
			instance->DONE_ACTIVITY = TRUE;
			On_Do(instance); /* Do of LIGHT_STATE_T_On */
			if( instance->DONE_ACTIVITY == FALSE ) {
				/* RTC reached. Do nothing more here. */;
			} else if( instance->EVENT == LIGHT_EVENT_T_Tick ) {
				/* On -> Off */
				instance->CURRENT_STATE_0 = LIGHT_STATE_T_Off;
				instance->EVENT = LIGHT_EVENT_T_NO_EVENT;
			} else {
				/* nothing */;
			}
			break; /* end of On */
		}
		default : break;
	} /* end of switch */
}

/**********************************************************************
 * state machine init code
 **********************************************************************/
void _basic_Light_init(STATEMACHINE *instance) {
	instance->FIRST = TRUE;
	instance->WALL_CLOCK = (WALLCLOCK_T)0;
	instance->CURRENT_STATE_0 = LIGHT_STATE_T_VOID;
	StateMachine_init(instance);
}

/**********************************************************************
 * state machine exit code
 **********************************************************************/
void _basic_Light_end(STATEMACHINE *instance) {
	StateMachine_end(instance);
}

/**********************************************************************
 * separate code of user-modifiable functions to prevent accidental
 * changes to code above.
 **********************************************************************/
#include "Light_usr.c"

/* end of file */
